name: BuildBattle
version: '1.0-SNAPSHOT'
main: org.mintype.buildBattle.BuildBattle
api-version: '1.21'
authors: [ Mintype ]
description: A mod for build battle in Minecraft.

commands:
  nightvision:
    description: Toggles night vision

  start:
    description: Starts the build battle game

  addtime:
    description: Adds time to the game

  reset:
    description: Resets the game

  floor:
    description: Sets your plot floor to the block you're holding
    usage: /floor

  teamsize:
    description: Sets the size of teams

  theme:
    description: Manage game theme
    usage: /theme set <theme> | /theme random | /theme reset

  resetplot:
    description: resets a plot by id.